# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MoviesStartProject' do

pod 'AFNetworking'

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MoviesStartProject


  target 'MoviesStartProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MoviesStartProjectUITests' do
    # Pods for testing
  end

end
